Importing the Libraries

In [18]:
import numpy as np
import pandas as pd

Q(1) --> Create an array of numbers from 0 to 9

In [2]:
array = list(np.arange(0,9))
print(array)

[0, 1, 2, 3, 4, 5, 6, 7, 8]


Q(2) --> Create a dictionary of your choice having 5 elements. Keys should be integer value


In [4]:
# Create a dictionary of your choice having 5 elements. Keys should be integer value

class intDict(dict):
  def __init__(self) :
    self = dict()

  def add_5_Element(self, key, value) :
    self[key] = value

objectDict = intDict()

objectDict.add_5_Element(1, 'Raftaar')
objectDict.add_5_Element(2, 'Rashedin')
objectDict.add_5_Element(3, 'Aman')
objectDict.add_5_Element(4, 'Jedy')
objectDict.add_5_Element(5, 'Reman')
print(objectDict)

{1: 'Raftaar', 2: 'Rashedin', 3: 'Aman', 4: 'Jedy', 5: 'Reman'}


Q(3) --> Create a dictionary of your choice having 5 elements. Keys should be string value

In [8]:
# Create a dictionary of your choice having 5 elements. Keys should be string value
class stringDict(dict) :
  def __init__(self) :
    self = dict()

  def add_5_String(self, key, value) :
    self[key] = value

objectStrDict = stringDict()

objectStrDict.add_5_String('Name ', 'Raftaar')
objectStrDict.add_5_String('Roll', '20BTCS038HY')
objectStrDict.add_5_String('Course', 'B.tech')
objectStrDict.add_5_String('College', 'Manuu')
objectStrDict.add_5_String('Contact', 'raftaarrashedin100@gmail.com')

print(objectStrDict)

{'Name ': 'Raftaar', 'Roll': '20BTCS038HY', 'Course': 'B.tech', 'College': 'Manuu', 'Contact': 'raftaarrashedin100@gmail.com'}


Q(4) --> Create list_1 for first 10 multiples of 5

Create list_2 for first 10 multiples of 3

Output list_3 should be such that it contains only even numbers from list_1 and list_2


In [9]:
multipleof5 = np.arange(5,51,5)
print(multipleof5)

[ 5 10 15 20 25 30 35 40 45 50]


In [11]:
multipleof3 = np.arange(3,31,3)
print(multipleof3)

[ 3  6  9 12 15 18 21 24 27 30]


In [17]:
even = multipleof5 + multipleof3
print(even)
# or
print("Another way ")
for num in even :
  if (num % 2 == 0) :
    print(num)

[ 8 16 24 32 40 48 56 64 72 80]
Another way 
8
16
24
32
40
48
56
64
72
80


(Dataset)
5. How many rows and columns are there in this dataset?
6. Print only column names in the dataset
7. Print first 10 observations
8. Create a new dataset by taking first 30 observations from this data


In [19]:
df = pd.read_csv('Sales_sample.csv')
df.head()

custId      custName                   custCountry productSold  \
0   23262  Candice Levy                         Congo     SUPA101   
1   23263  Xerxes Smith                        Panama     DETA200   
2   23264  Levi Douglas  Tanzania, United Republic of     DETA800   
3   23265  Uriel Benton                  South Africa     SUPA104   
4   23266  Celeste Pugh                         Gabon     PURA200   

  salesChannel  unitsSold    dateSold  
0       Retail        117  08-09-2012  
1       Online         73  07-06-2012  
2       Online        205   8/18/2012  
3       Online         14  08-05-2012  
4       Retail        170  08-11-2012

In [22]:
print("Row",df.shape,"column")

Row (11, 7) column


In [25]:
columnname = df.columns
print(columnname)

Index(['custId', 'custName', 'custCountry', 'productSold', 'salesChannel',
       'unitsSold', 'dateSold'],
      dtype='object')


In [26]:
df.head(10)

custId            custName                   custCountry productSold  \
0   23262        Candice Levy                         Congo     SUPA101   
1   23263        Xerxes Smith                        Panama     DETA200   
2   23264        Levi Douglas  Tanzania, United Republic of     DETA800   
3   23265        Uriel Benton                  South Africa     SUPA104   
4   23266        Celeste Pugh                         Gabon     PURA200   
5   23267        Vance Campos          Syrian Arab Republic     PURA100   
6   23268        Latifah Wall                    Guadeloupe     DETA100   
7   23269      Jane Hernandez                     Macedonia     PURA100   
8   23270         Wanda Garza                    Kyrgyzstan     SUPA103   
9   23271  Athena Fitzpatrick                       Reunion     SUPA103   

  salesChannel  unitsSold    dateSold  
0       Retail        117  08-09-2012  
1       Online         73  07-06-2012  
2       Online        205   8/18/2012  
3       Online         14  08-05-2012  
4       Retail        170  08-11-2012  
5       Retail        129  07-11-2012  
6       Retail         82  07-12-2012  
7       Retail        116  06-03-2012  
8       Online         67  06-07-2012  
9       Retail        125   7/27/2012

In [30]:
# Getting first 3 rows from df
df1 = df.iloc[:30]
  
# Printing df_first_3
df1.head()

custId            custName                   custCountry productSold  \
0    23262        Candice Levy                         Congo     SUPA101   
1    23263        Xerxes Smith                        Panama     DETA200   
2    23264        Levi Douglas  Tanzania, United Republic of     DETA800   
3    23265        Uriel Benton                  South Africa     SUPA104   
4    23266        Celeste Pugh                         Gabon     PURA200   
5    23267        Vance Campos          Syrian Arab Republic     PURA100   
6    23268        Latifah Wall                    Guadeloupe     DETA100   
7    23269      Jane Hernandez                     Macedonia     PURA100   
8    23270         Wanda Garza                    Kyrgyzstan     SUPA103   
9    23271  Athena Fitzpatrick                       Reunion     SUPA103   
10   23271       Anjolie Hicks      Turks and Caicos Islands     DETA200   

   salesChannel  unitsSold    dateSold  
0        Retail        117  08-09-2012  
1        Online         73  07-06-2012  
2        Online        205   8/18/2012  
3        Online         14  08-05-2012  
4        Retail        170  08-11-2012  
5        Retail        129  07-11-2012  
6        Retail         82  07-12-2012  
7        Retail        116  06-03-2012  
8        Online         67  06-07-2012  
9        Retail        125   7/27/2012  
10       Retail         71   7/31/2012